Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/05/2019
Var
// Seção de Declarações das variáveis 

n1,n2,s: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

s <- 0
escreva("Informe os números: ")
leia(n1,n2)

s <- s+(n1+n2)
escreval("Soma = ", s)

Fimalgoritmo